add loan and disbursement  api function
koinworks/node-sdk pull request #5
Opened 2022-08-16 03:56 UTC by fitriawans

loan and disbursement api
- Verify Loan OTP
- Loan Partner Cancelled
- Delivery Confirmation
- Loan Disbursement Report
- Repayment

2022-08-16 04:19 UTC, rilexkoinworks requested changes

2022-08-16 04:19 UTC, rilexkoinworks commented on test/middleware.js
> +    // const options = setOptions(payload,"requestLimit");
remove comments

2022-08-16 04:22 UTC, fitriawans commented on test/middleware.js
> +    // const options = setOptions(payload,"requestLimit");
itu buat ngetest mas maksudnya supaya tinggal dienable aja waktu mau test, diremove aja brrti ya sisain yg terakhir ditest?

2022-08-16 04:28 UTC, rilexkoinworks commented on test/middleware.js
> +    // const options = setOptions(payload,"requestLimit");
salah satu saja, lalu buat juga negative case nya dengan value yg tidak terdefine di config

2022-08-22 04:57 UTC, rilexkoinworks approved these changes

2022-08-22 04:57 UTC, merged